### ISSUE TITLE
Won't compile on Debian Sid

### ISSUE THREAD

**Issue by brokechubb** [hb9xar/TNT#1]
Linux hamshack 5.10.0-8-amd64 #1 SMP Debian 5.10.46-1 (2021-06-24) x86_64 GNU/Linux

```
[~/src/TNT]:hamshack $ make dep
gcc -E -M -funsigned-char -O2 -DTNT_LINUX main.c serial.c keyboard.c display.c window.c file.c codconv.c init.c remote.c cookie.c crc.c shell.c macro.c connect.c log.c iface.c xmon.c monbox.c boxlist.c priv.c comp.c bcastadd.c bcast.c huffman.c yapp.c > .depend
[~/src/TNT]:hamshack $ make
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o main.o main.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o serial.o serial.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o keyboard.o keyboard.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o display.o display.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o window.o window.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o file.o file.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o codconv.o codconv.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o init.o init.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o remote.o remote.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o cookie.o cookie.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o crc.o crc.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o shell.o shell.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o macro.o macro.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o connect.o connect.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o log.o log.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o iface.o iface.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o xmon.o xmon.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o monbox.o monbox.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o boxlist.o boxlist.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o priv.o priv.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o comp.o comp.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o bcastadd.o bcastadd.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o bcast.o bcast.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o huffman.o huffman.c
gcc -funsigned-char -O2 -DTNT_LINUX   -c -o yapp.o yapp.c
gcc -funsigned-char -O2 -DTNT_LINUX main.o serial.o keyboard.o display.o window.o file.o codconv.o init.o remote.o cookie.o crc.o shell.o macro.o connect.o log.o iface.o xmon.o monbox.o boxlist.o priv.o comp.o bcastadd.o bcast.o huffman.o yapp.o -ltermcap -o tnt;
/usr/bin/ld: bcastadd.o:(.bss+0x20): multiple definition of `bcast_log_file'; init.o:(.bss+0x5c0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:143: tnt] Error 1

```

**Comment by hb9xar** [comment]
Builds fine with Centos 7 (gcc 4.8.5) and Ubuntu 20.04.2 LTS (gcc 9.3.0). What gcc version are you using?

Would the following patch fix your compile issue?
```
diff --git a/bcastadd.c b/bcastadd.c
index 47a5fa2..038e250 100644
--- a/bcastadd.c
+++ b/bcastadd.c
@@ -66,7 +66,7 @@ extern char tnt_dir[];
 int shpacsat_flag;
 int bcrequest_flag;
 int decbcast_flag;
-char bcast_log_file[80];
+extern char bcast_log_file[];
 bccbtype func_callback;
```

**Comment by brokechubb** [comment]
Here is the gcc version.

how would i apply the patch?

```
[~/src/TNT]:hamshack $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 
```

**Comment by brokechubb** [comment]
nevermind, i manually changed the code and it worked.

**Comment by hb9xar** [comment]
I can confirm it's related to the GCC version. GCC version 10.3.0 does produce this error during link stage, earlier GCC versions do not.

fixed with a37e219c7c1721c5cb900792b036dfc9bee0ba87
